import Vue from 'vue'
import { Button, Icon, Tabbar, TabbarItem, NavBar, Field, CellGroup, Form, CountDown, Image as VanImage, Grid, GridItem, Cell, Tab, Tabs, List, PullRefresh, Popup, Search } from 'vant'

Vue.use(Button)
Vue.use(Icon)
Vue.use(Tabbar)
Vue.use(TabbarItem)
Vue.use(NavBar)
Vue.use(Form)
Vue.use(Field)
Vue.use(CellGroup)
Vue.use(CountDown)
Vue.use(VanImage)
Vue.use(Grid)
Vue.use(GridItem)
Vue.use(Cell)
Vue.use(Tab)
Vue.use(Tabs)
Vue.use(List)
Vue.use(PullRefresh)
Vue.use(Popup)
Vue.use(Search)
